// <auto-generated />
using System;
using Blace.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blace.Server.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20260330140528_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blace.Shared.Models.Delete", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("DateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Deletes");
                });

            modelBuilder.Entity("Blace.Shared.Models.PlaceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("CreatedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("LastChangeTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("places", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("PlaceInfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Blace.Shared.Models.Tile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<byte>("Color")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<byte>("PreviousColor")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeleteId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlaceId", "UserId");

                    b.HasIndex("PlaceId", "X", "Y");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Blace.Shared.Models.Place", b =>
                {
                    b.HasBaseType("Blace.Shared.Models.PlaceInfo");

                    b.Property<byte[]>("Canvas")
                        .HasColumnType("bytea");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Place");
                });
#pragma warning restore 612, 618
        }
    }
}
